services:
  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ikinyamakuru
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: ikinyamakuru
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ikinyamakuru"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
