services:
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: ikinyamakuru-api
  #   container_name: ikinyamakuru-api
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - postgres
  #   networks:
  #     - default
  postgres:
    image: postgres:16-alpine
    container_name: ikinyamakuru-pg
    restart: always
    environment:
      POSTGRES_USER: ikinyamakuru
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: ikinyamakuru
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ikinyamakuru"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  adminer:
    image: adminer:4.8.1
    container_name: ikinyamakuru-adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres

    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
